name: Test Suite
on:
  schedule:
    - cron: '30 3,11 * * *'
    # 9:00 AM IST is 3:30 AM UTC.
    # 5:00 PM IST is 11:30 AM UTC.
  push:
    branches:
      - main
  pull_request:
    branch:
      - main
  workflow_dispatch:

jobs:
  UI_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout main branch'
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Install Playwright browsers'
        run: npx playwright install --with-deps
      - name: 'Run UI tests'
        run: npm run test-ui
        env:
          CI: 'true'
      - name: 'Rerun UI tests'
        run: npm run test-ui:failed
        env:
          CI: 'true'
        if: failure()
      - name: 'Generate reports'
        run: npm run ui-report-gen
        env:
          CI: 'true'
      - name: 'Upload a Build Artifact'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ui-artifact
          path: |
            test-results
            traces
            logging
        if: always()
      - name: Set up and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          git commit --allow-empty -m "Initial commit to gh-pages"
          git push --set-upstream origin gh-pages
      - name: Publish Report per branch
        uses: mgrybyk-org/html-trend-report-action@v1.2.2
        with:
          report_id: UI Test Report
          gh_pages: gh_pages
          report_dir: './test-results/json-reports/'
          report_type: html
  API_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout main branch'
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Run API tests'
        run: npm run test-api
        env:
          CI: 'true'
      - name: 'Upload a Build Artifact'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: api-artifact
          path: |
            logging
        if: always()
  K6_tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout main branch'
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Install dependencies'
        run: npm install
      - name: 'Install K6'
        uses: grafana/setup-k6-action@v1
      - name: 'Run K6 tests'
        run: npm run test-k6
        env:
          CI: 'true'
            
        
